### ISSUE TITLE
Magical Crops Integration

### ISSUE THREAD

**Issue by canitzp** [tterrag1098/WAILAPlugins#57] opened 2015-09-16 14:53 UTC
WailaPlugins crashed if I use a older Version of Magical Crops, because Magical Crops chnaged IDs and the user of my Modpack want to use their old World.
Here is the Crash-Report: http://pastebin.com/7Rrw004H

**Comment by tterrag1098** [comment] 2015-09-16 19:29
Duplicate of #54

**Closed by tterrag1098** 2015-09-16 19:29 UTC
